var searchData=
[
  ['setaccelerationvolume',['setAccelerationVolume',['../r_t_tracer_2source_2describers_8cu.html#a62894bfe2e9e2b1cd55216c772eafb27',1,'describers.cu']]],
  ['setcubeaccelerationvolume',['setCubeAccelerationVolume',['../group__intersection__test__prperties.html#gabfac85fdf9d0cceb70aefa4c2ed71ad2',1,'setCubeAccelerationVolume(const DevObject *currentObject, Boundaries *boundaries, Vec3f(&amp;boundingPlaneNormals)[7], float *(&amp;gpu_allDotProducts)[7]):&#160;describers.cu'],['../group__intersection__test__prperties.html#gabfac85fdf9d0cceb70aefa4c2ed71ad2',1,'setCubeAccelerationVolume(const DevObject *currentObject, Boundaries *boundaries, Vec3f(&amp;boundingPlaneNormals)[7], float *(&amp;gpu_allDotProducts)[7]):&#160;describers.cu'],['../group__intersection__test__prperties.html#gabfac85fdf9d0cceb70aefa4c2ed71ad2',1,'setCubeAccelerationVolume(const DevObject *currentObject, Boundaries *boundaries, Vec3f(&amp;boundingPlaneNormals)[7], float *(&amp;gpu_allDotProducts)[7]):&#160;describers.cu']]],
  ['setmeshaccelerationvolume',['setMeshAccelerationVolume',['../group__intersection__test__prperties.html#ga672ecbee3aea2f5567ad7a2611feef3e',1,'setMeshAccelerationVolume(const DevObject *currentObject, Boundaries *boundaries, Vec3f(&amp;boundingPlaneNormals)[7], float *(&amp;gpu_allDotProducts)[7]):&#160;describers.cu'],['../group__intersection__test__prperties.html#ga672ecbee3aea2f5567ad7a2611feef3e',1,'setMeshAccelerationVolume(const DevObject *currentObject, Boundaries *boundaries, Vec3f(&amp;boundingPlaneNormals)[7], float *(&amp;gpu_allDotProducts)[7]):&#160;describers.cu'],['../group__intersection__test__prperties.html#ga672ecbee3aea2f5567ad7a2611feef3e',1,'setMeshAccelerationVolume(const DevObject *currentObject, Boundaries *boundaries, Vec3f(&amp;boundingPlaneNormals)[7], float *(&amp;gpu_allDotProducts)[7]):&#160;describers.cu']]],
  ['setplaneaccelerationvolume',['setPlaneAccelerationVolume',['../group__intersection__test__prperties.html#ga684f41eb2add27e32a7c0115cdd6cce1',1,'setPlaneAccelerationVolume(const DevObject *currentObject, Boundaries *boundaries, Vec3f(&amp;boundingPlaneNormals)[7], float *(&amp;gpu_allDotProducts)[7]):&#160;describers.cu'],['../group__intersection__test__prperties.html#ga684f41eb2add27e32a7c0115cdd6cce1',1,'setPlaneAccelerationVolume(const DevObject *currentObject, Boundaries *boundaries, Vec3f(&amp;boundingPlaneNormals)[7], float *(&amp;gpu_allDotProducts)[7]):&#160;describers.cu'],['../group__intersection__test__prperties.html#ga684f41eb2add27e32a7c0115cdd6cce1',1,'setPlaneAccelerationVolume(const DevObject *currentObject, Boundaries *boundaries, Vec3f(&amp;boundingPlaneNormals)[7], float *(&amp;gpu_allDotProducts)[7]):&#160;describers.cu']]],
  ['setsphereaccelerationvolume',['setSphereAccelerationVolume',['../group__intersection__test__prperties.html#gafd2f15ce4a55fb0d8daee0bff024b67b',1,'setSphereAccelerationVolume(const DevObject *currentObject, Boundaries *boundaries, Vec3f(&amp;boundingPlaneNormals)[7], float *(&amp;gpu_allDotProducts)[7]):&#160;describers.cu'],['../group__intersection__test__prperties.html#gafd2f15ce4a55fb0d8daee0bff024b67b',1,'setSphereAccelerationVolume(const DevObject *currentObject, Boundaries *boundaries, Vec3f(&amp;boundingPlaneNormals)[7], float *(&amp;gpu_allDotProducts)[7]):&#160;describers.cu'],['../group__intersection__test__prperties.html#gafd2f15ce4a55fb0d8daee0bff024b67b',1,'setSphereAccelerationVolume(const DevObject *currentObject, Boundaries *boundaries, Vec3f(&amp;boundingPlaneNormals)[7], float *(&amp;gpu_allDotProducts)[7]):&#160;describers.cu']]],
  ['sphereproperties',['sphereProperties',['../group__intersection__test__prperties.html#gae821d5671069271f7c39d22ca8950f3d',1,'sphereProperties(const DevObject &amp;object, const Vec3f &amp;hitPoint, GPU::RenderingContext &amp;ctx, Vec2f &amp;hitTextureCoordinates):&#160;describers.cu'],['../group__intersection__test__prperties.html#gae821d5671069271f7c39d22ca8950f3d',1,'sphereProperties(const DevObject &amp;object, const Vec3f &amp;hitPoint, GPU::RenderingContext &amp;ctx, Vec2f &amp;hitTextureCoordinates):&#160;describers.cu'],['../group__intersection__test__prperties.html#gae821d5671069271f7c39d22ca8950f3d',1,'sphereProperties(const DevObject &amp;object, const Vec3f &amp;hitPoint, GPU::RenderingContext &amp;ctx, Vec2f &amp;hitTextureCoordinates):&#160;describers.cu']]],
  ['spiral',['spiral',['../group__linear__algebra.html#gac9237c364274b9a0fbb9184fae573357',1,'spiral(const float &amp;t, const float &amp;R, const float &amp;S):&#160;geom.cu'],['../group__linear__algebra.html#gac9237c364274b9a0fbb9184fae573357',1,'spiral(const float &amp;t, const float &amp;R, const float &amp;S):&#160;geom.cu'],['../group__linear__algebra.html#gac9237c364274b9a0fbb9184fae573357',1,'spiral(const float &amp;t, const float &amp;R, const float &amp;S):&#160;geom.cu']]],
  ['strips',['strips',['../group__intersection__test__prperties.html#gae0b690ff7b5f9b93e53bb0c1437fbf55',1,'strips(const Vec2f &amp;hitTexCoordinates):&#160;describers.cu'],['../group__intersection__test__prperties.html#gae0b690ff7b5f9b93e53bb0c1437fbf55',1,'strips(const Vec2f &amp;hitTexCoordinates):&#160;describers.cu'],['../group__intersection__test__prperties.html#gae0b690ff7b5f9b93e53bb0c1437fbf55',1,'strips(const Vec2f &amp;hitTexCoordinates):&#160;describers.cu']]],
  ['swap',['swap',['../group__auxiliary__algorithms.html#ga8bffe5209ec351179a96aed81aab0978',1,'algorithms']]]
];
